### DISCUSSION TITLE
missing previous/next buttons in carousel view

### DISCUSSION THREAD

**Discussion by h4de5** [cbenning/fussel#102] [General]
in the latest version it seems the next and previous buttons are gone: 

it's still possible to navigate using arrow keys - but when you click outside the actual image, the modal closes.

![image](https://user-images.githubusercontent.com/6115324/105819937-2ccaaa80-5fb9-11eb-8e05-beb794b8a03b.png)

**Comment by cbenning** [comment]
Hmm. I upgraded the dependency and didn't notice this. But the package appears to be abandonware. I will test this and see if I can reproduce ite.

**Comment by despair86** [comment]
the carousel no longer works correctly outside of mobile browsers - on a desktop browser the carousel appears _below_ the modal dialogue out of sight
the image will even flash for a split second before the dialogue covers it!

**Comment by cbenning** [comment]
@despair86 the UI tool was abandoned. I've re-written the entire frontend using new components and can be tested out on the v2 branch before it is released if interested

**Comment by h4de5** [comment]
any chance for an updated docker image? or a beta docker release?

**Comment by cbenning** [comment]
@h4de5 I'll make a task and try to get to it in the next day or two if I can find time. Good suggestion.

**Comment by cbenning** [comment]
@h4de5 give this a try:

```
docker run \
      -e PGID=$(id -g) \
      -e PUID=$(id -u) \
      -v <input_dir>:/input:ro \
      -v <output_dir>:/output \
      --label gallery.input_path="/input" \
      --label gallery.output_path="/output" \
      --label gallery.overwrite=False \
      --label albums.recursive=True \
      --label albums.recursive_name_pattern="{parent_album} > {album}" \
      --label people.enable=True \
      --label watermark.enable=True \
      --label watermark.path="web/src/images/fussel-watermark.png" \
      --label watermark.size_ratio=0.3 \
      --label site.http_root="/" \
      --label site.title="Fussel Gallery" \
     -v /var/run/docker.sock:/var/run/docker.sock \
     ghcr.io/cbenning/fussel:2.0.0-rc4
```

**Comment by h4de5** [comment]
is it possible that this image is set to private?

**Comment by cbenning** [comment]
@h4de5 yup sorry. Still getting the hang of using ghcr.io. Should be fixed now, give it a try.

**Comment by h4de5** [comment]
image is now download able, but running failed. just gave it a brief test run, will have a look at my config later on, to check if it is on my side.

![Screenshot_20230216-005854](https://user-images.githubusercontent.com/6115324/219222613-83f4bf09-3daa-4a75-9157-a3ca24546922.png)

**Reply by cbenning** [reply]
My guess is that you did not add this `-v /var/run/docker.sock:/var/run/docker.sock \` to your docker compose? Allowing the socket into the container is the only way to use the labels to generate the config. I decided it was a reasonable compromise in security since this is not a long-running container.

**Comment by cbenning** [comment]
It kinda looks like its failing to generate the config. Looks lke you're using docker-compose? Mind sharing your config?

**Comment by h4de5** [comment]
sorry for letting you wait - only got a chance to properly test it.

docker-compose.yaml:

```yaml
version: "3"
services:
  fussel:
    image: "ghcr.io/cbenning/fussel:latest"
    # image: "ghcr.io/cbenning/fussel:2.0.0-rc4"
    # image: "ghcr.io/cbenning/fussel:2.0.1"
    environment:
      - PGID=100
      - PUID=1024
    volumes:
      - "/volume1/photo/albums:/input:ro"
      - "/volume1/web/homepage:/output"
      - "/var/run/docker.sock:/var/run/docker.sock"
    labels:
      - gallery.input_path=/input
      - gallery.output_path=/output
      - gallery.overwrite=True
      - albums.recursive=False
      - people.enable=False
      - watermark.enable=False
      - site.http_root=/
      - "site.title=Family Albums"
```

error output:

```bash
docker-compose up
Starting docker-fussel_fussel2_1 ... done
Attaching to docker-fussel_fussel2_1
fussel2_1  | /fussel /
fussel2_1  | Generating yaml config...
fussel2_1  | Traceback (most recent call last):
fussel2_1  |   File "/fussel/utils/./flat_json_to_nested_json.py", line 19, in <module>
fussel2_1  |     cursor[segment] = {}
fussel2_1  | TypeError: 'str' object does not support item assignment
fussel2_1  |
fussel2_1  | Traceback (most recent call last):
fussel2_1  |   File "/fussel/fussel/./fussel.py", line 83, in <module>
fussel2_1  |     main()
fussel2_1  |   File "/fussel/fussel/./fussel.py", line 41, in main
fussel2_1  |     cfg = YamlConfig()
fussel2_1  |   File "/fussel/fussel/./fussel.py", line 17, in __init__
fussel2_1  |     input_path = self.getKey('gallery.input_path')
fussel2_1  |   File "/fussel/fussel/./fussel.py", line 28, in getKey
fussel2_1  |     if path in self.cfg:
fussel2_1  | TypeError: argument of type 'NoneType' is not iterable
fussel2_1  | Fixing permissions...
fussel2_1  | chown: null: No such file or directory
docker-fussel_fussel2_1 exited with code 1
```

there are currently 10 folders with each around 10 to 50 images within `/volume1/photo/albums`. there is also an `.ini` file and an `@eaDir` folder within each of those directories (in case this might break stuff..)

**Comment by h4de5** [comment]
appearentally my docker-compose was wrong .. running with your command works.

```bash
docker run \
      -e PGID=$(id -g) \
      -e PUID=$(id -u) \
      -v "/volume1/photo/albums:/input:ro" \
      -v "/volume1/web/homepage:/output" \
      --label gallery.input_path="/input" \
      --label gallery.output_path="/output" \
      --label gallery.overwrite=True \
      --label albums.recursive=False \
      --label people.enable=False \
      --label watermark.enable=False \
      --label site.http_root="/" \
      --label site.title="Family Gallery" \
     -v /var/run/docker.sock:/var/run/docker.sock \
     ghcr.io/cbenning/fussel:latest
```

also next and previous buttons are there in the image detail.


even after trying to comply with the documentation for labels, i had no luck so far: 

https://docs.docker.com/compose/compose-file/compose-file-v3/#labels-1

anyways - issue can be closed. once I have a solution for docker-compose I may update this thread.

thanks for your work!

**Comment by h4de5** [comment]
works with mounting `config.yml` directly in the container:

download `sample_config.yml`, modify it and place it as `config.yml` next to the `docker-compose.yml` file. 
leave the labels.

```yaml
version: "3"
services:
  fussel:
    image: "ghcr.io/cbenning/fussel:latest"
    container_name: fussel_gallery
    environment:
      - PGID=100
      - PUID=1024
    volumes:
      - "/volume1/photo/albums:/input:ro"
      - "/volume1/web/gallery:/output"
      - "./config.yml:/fussel/config.yml:ro"
      - "/var/run/docker.sock:/var/run/docker.sock"
```
