### ISSUE TITLE
Invalid label tags in documentation

### ISSUE THREAD

**Issue by h4de5** [cbenning/fussel#105]
documentation says "albums.recursive"
https://github.com/cbenning/fussel/blob/20c853f03b2a9a0db3e78b29bd6ad93cbd6477f8/README.md?plain=1#L122

but config is read from "gallery.albums.recursive"
https://github.com/cbenning/fussel/blob/20c853f03b2a9a0db3e78b29bd6ad93cbd6477f8/fussel/generator/config.py#L39

same with most other label parameters.

**Comment by h4de5** [comment]
even when providing correct labels, the values are somehow ignored:

on docker run:
```
  --label gallery.input_path="/input" \
  --label gallery.output_path="/output" \
  --label gallery.overwrite=True \
  --label gallery.albums.recursive=False \
  --label gallery.people.enable=False \
  --label gallery.watermark.enable=False \
  --label site.http_root="/" \
  --label site.title="Family Album" \
```

correctly transfered into container:

```
Generating yaml config...
gallery:
  albums:
    recursive: "False"
  input_path: /input
  output_path: /output
  overwrite: "True"
  people:
    enable: "False"
  watermark:
    enable: "False"
org:
  opencontainers:
    image:
      description: 'A static photo gallery generator '
      licenses: MIT
      source: https://github.com/cbenning/fussel
site:
  http_root: /
  title: Family Album
Generating site from /input
```

generator still processes sub-directories and adds watermark.
