### ISSUE TITLE
Docker install error

### ISSUE THREAD

**Issue by tehniemer** [cbenning/fussel#28]
I'm getting this error when starting the container. Any idea what it means or how to correct it?
```
ImportError: cannot import name 'UnidentifiedImageError' from 'PIL' (/usr/lib/python3.8/site-packages/PIL/__init__.py)
```

**Comment by cbenning** [comment]
That's new. I suspect its an invalid image format that I didn't handle properly in the code. What type of files are you using?

**Comment by tehniemer** [comment]
It's all .jpg files with the exception of a single .txt file for another application that also uses the same directory.

**Comment by tehniemer** [comment]
I just tried changing the ```/input``` directory to one that only contains ```.jpg``` files and I get the same error.

**Comment by cbenning** [comment]
Is there more to the stack trace per chance?

**Comment by cbenning** [comment]
Looking at other instances of this error online, it might indicate an incorrectly installed "Pillow" library. Example: https://github.com/home-assistant/core/issues/32953

**Comment by tehniemer** [comment]
This is the whole log
```
/,
Using config: ,
,
INPUT_PATH=/input,
HTTP_ROOT=https://fussel.tehniemer.com/,
OVERWRITE=false,
WATERMARK_ENABLE=false,
PEOPLE_ENABLE=true,
WATERMARK_PATH="web/src/images/fussel-watermark.png",
WATERMARK_RATIO=0.3,
SITE_NAME=Fussel Gallery,
RECURSIVE_ALBUMS_NAME_PATTERN={parent_album} > {album},
RECURSIVE_ALBUMS=true,
Traceback (most recent call last):,
  File "./fussel.py", line 5, in <module>,
    from generator import SiteGenerator,
  File "/fussel/generator/__init__.py", line 1, in <module>,
    from .generate import *,
  File "/fussel/generator/generate.py", line 6, in <module>,
    from PIL import Image, UnidentifiedImageError,
ImportError: cannot import name 'UnidentifiedImageError' from 'PIL' (/usr/lib/python3.8/site-packages/PIL/__init__.py),
Fixing permissions...,
\nExtra docker instructions:,
 To validate build run:,
   python -m http.server --directory <your-output-mapping>
```

**Comment by tehniemer** [comment]
Here's the snippet from my compose file if that's of any use.

```
## Fussel - Image Gallery
  fussel:
    image: cbenning/fussel:latest
    container_name: fussel
    restart: unless-stopped
    networks:
      - proxy
    security_opt:
      - no-new-privileges:true
    ports:
      - "$FUSSEL_PORT:8000"
    environment:
      PUID: $PUID
      PGID: $PGID
      INPUT_PATH: "/input"
      HTTP_ROOT: "https://fussel.$DOMAINNAME/"
      OVERWRITE: "false"
      PEOPLE_ENABLE: "true"
      WATERMARK_ENABLE: "false"
      WATERMARK_PATH: "web/src/images/fussel-watermark.png"
      WATERMARK_RATIO: 0.3
      SITE_NAME: "Fussel Gallery"
      RECURSIVE_ALBUMS: "true"
      RECURSIVE_ALBUMS_NAME_PATTERN: "{parent_album} > {album}"
    volumes:
      - "fussel:/fussel/web/build"
      - "$PHOTO_DIR/_EXPORTS/Collections:/input:ro"
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"
    labels:
      - "traefik.enable=false"
      ## HTTP Routers
      - "traefik.http.routers.fussel-rtr.entrypoints=https"
      - "traefik.http.routers.fussel-rtr.rule=HostHeader(`fussel.$DOMAINNAME`)"
      - "traefik.http.routers.fussel-rtr.tls=true"
      ## Middlewares
#      - "traefik.http.routers.fussel-rtr.middlewares=chain-no-auth@file" #No Authentication
#      - "traefik.http.routers.fussel-rtr.middlewares=chain-basic-auth@file" #Basic Authentication
#      - "traefik.http.routers.fussel-rtr.middlewares=chain-oauth@file" #Google OAuth 2.0
#      - "traefik.http.routers.fussel-rtr.middlewares=chain-organizr@file" #Organizr Authentication
      - "traefik.http.routers.fussel-rtr.middlewares=chain-authelia@file" #Authelia Authentication
      ## HTTP Services
      - "traefik.http.routers.fussel-rtr.service=fussel-svc"
      - "traefik.http.services.fussel-svc.loadbalancer.server.port=8000"
```
